version: 1.0.{build}
image: Visual Studio 2017
environment:
  matrix:
  - COMPILER: msys2
    PLATFORM: x64
    MSYS2_ARCH: x86_64
    MSYS2_DIR: msys64
    MSYSTEM: MINGW64
    BIT: 64

build_script:
- cmd: >-
    SET "PATH=C:\%MSYS2_DIR%\%MSYSTEM%\bin;C:\%MSYS2_DIR%\usr\bin;%PATH

    bash -lc "pacman -R --noconfirm catgets libcatgets"

    bash -lc "pacman -Syu --noconfirm"

    bash -lc "pacman -Sy --needed --noconfirm base-devel mpfr cmake mingw64/mingw-w64-x86_64-glib2 glib2-devel mingw64/mingw-w64-x86_64-cairo mingw64/mingw-w64-x86_64-gst-plugins-base mingw64/mingw-w64-x86_64-gst-plugins-good mingw64/mingw-w64-x86_64-gst-plugins-bad mingw64/mingw-w64-x86_64-gtk3 mingw64/mingw-w64-x86_64-pango mingw-w64-x86_64-lua mingw64/mingw-w64-x86_64-libsoup"

    bash -lc "cd /c/projects/ginga && ./bootstrap && ./configure --disable-shared && make -j4"

notifications:
- provider: Email
  to:
  - alan@telemidia.puc-rio.br
  - gflima@telemidia.puc-rio.br
  - robertogerson@telemidia.puc-rio.br
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: true
